[project]
name = "typer"
version = "0.1.0"
description = "A game inspired by github.com/thecodeah/space-typer"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "arcade>=3.3.2",
    "ruff>=0.12.7",
]

[tool.ruff]
ignore = ["F405", "E401", "F403"]
